### ISSUE TITLE
psvimgtools-frontend Not connecting to henkaku.xyz server

### ISSUE THREAD

**Issue by hummed007** [SilicaAndPina/psvimgtools-frontend#83]
![adadadadad](https://user-images.githubusercontent.com/39050763/39695929-9e1b9466-5205-11e8-86f9-dc6e7b7b927b.png)
PLZ HELP ME

**Comment by SilicaAndPina** [comment]
can you access http://cma.henkaku.xyz?

**Comment by hummed007** [comment]
Yes I can

**Comment by acortez03** [comment]
I am also having this same issue. The psvimgtools-frontend also crashes after a few seconds. I am using a windows x64 bit system. Has anyone found a fix? Thanks in advance!

**Comment by SilicaAndPina** [comment]
possibly molecule got mad and decided to block urllib from accessing cma.henkaku.xyz, though i dont think this is the case i can add stuff just fine on mine. (and they probably know how easily i could get around that anyway. . .) 
its also possible your browser / computer has some network configuration that urllib is simply not using *such as a proxy server, or authentication crap. in which case..  im not quite sure what to do maybe add the option to add **KEYS** manually w/o just asking for AID's and finding the keys, but you allready can by messing with the files enough . - .*

- acortez03 your issue is likely due to radziu dropping NPS .csv support please try using 0.6.1
